//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.ClasStars.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ColorsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.ClasStars.Resources.ColorsResource", typeof(ColorsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF8C2B.
        /// </summary>
        public static string AcademicNegativeColor {
            get {
                return ResourceManager.GetString("AcademicNegativeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FDCD21.
        /// </summary>
        public static string AcademicPositiveColor {
            get {
                return ResourceManager.GetString("AcademicPositiveColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #5667A7.
        /// </summary>
        public static string AppBlueOcean80Color {
            get {
                return ResourceManager.GetString("AppBlueOcean80Color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #393939.
        /// </summary>
        public static string AppDarkGrayColor {
            get {
                return ResourceManager.GetString("AppDarkGrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #2B4091.
        /// </summary>
        public static string AppDeepBlueOcean100Color {
            get {
                return ResourceManager.GetString("AppDeepBlueOcean100Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #8C8C8C.
        /// </summary>
        public static string AppGrayColor {
            get {
                return ResourceManager.GetString("AppGrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #218A1F.
        /// </summary>
        public static string AppGreenColor {
            get {
                return ResourceManager.GetString("AppGreenColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #808DBD.
        /// </summary>
        public static string AppLightBlueOcean60Color {
            get {
                return ResourceManager.GetString("AppLightBlueOcean60Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D1D3D4.
        /// </summary>
        public static string AppLightGrayColor {
            get {
                return ResourceManager.GetString("AppLightGrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FF8C2B.
        /// </summary>
        public static string AppOrangeColor {
            get {
                return ResourceManager.GetString("AppOrangeColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D32629.
        /// </summary>
        public static string AppRedColor {
            get {
                return ResourceManager.GetString("AppRedColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #f1f1f1.
        /// </summary>
        public static string AppSurfaceBorderColor {
            get {
                return ResourceManager.GetString("AppSurfaceBorderColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #fdffff.
        /// </summary>
        public static string AppSurfaceColor {
            get {
                return ResourceManager.GetString("AppSurfaceColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #2d374b29.
        /// </summary>
        public static string AppSurfaceShadowColor {
            get {
                return ResourceManager.GetString("AppSurfaceShadowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #61BAFD.
        /// </summary>
        public static string AppSkyBlueColor {
            get {
                return ResourceManager.GetString("AppSkyBlueColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #FDCD21.
        /// </summary>
        public static string AppYellowColor {
            get {
                return ResourceManager.GetString("AppYellowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #5D7899.
        /// </summary>
        public static string LightSteelGrayColor {
            get {
                return ResourceManager.GetString("LightSteelGrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #D32629.
        /// </summary>
        public static string NegativeBehaviorColor {
            get {
                return ResourceManager.GetString("NegativeBehaviorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #218A1F.
        /// </summary>
        public static string PositiveBehaviorColor {
            get {
                return ResourceManager.GetString("PositiveBehaviorColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3E5066.
        /// </summary>
        public static string SteelGrayColor {
            get {
                return ResourceManager.GetString("SteelGrayColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #3E5067.
        /// </summary>
        public static string SteelGrayColor2 {
            get {
                return ResourceManager.GetString("SteelGrayColor2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #ededed.
        /// </summary>
        public static string AppSidebarBackgroundColor {
            get {
                return ResourceManager.GetString("AppSidebarBackgroundColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #ffffff.
        /// </summary>
        public static string AppWhiteColor {
            get {
                return ResourceManager.GetString("AppWhiteColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #999999.
        /// </summary>
        public static string AppIconGrayColor {
            get {
                return ResourceManager.GetString("AppIconGrayColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #f7f7f7.
        /// </summary>
        public static string AppLightSurfaceColor {
            get {
                return ResourceManager.GetString("AppLightSurfaceColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #f2f5ff.
        /// </summary>
        public static string AppInputBackgroundColor {
            get {
                return ResourceManager.GetString("AppInputBackgroundColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #d7d7d7.
        /// </summary>
        public static string AppBorderNeutralColor {
            get {
                return ResourceManager.GetString("AppBorderNeutralColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #FAF9F8.
        /// </summary>
        public static string AppSurfaceAltColor {
            get {
                return ResourceManager.GetString("AppSurfaceAltColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #201F1E.
        /// </summary>
        public static string AppSurfaceDarkColor {
            get {
                return ResourceManager.GetString("AppSurfaceDarkColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #1E90FF.
        /// </summary>
        public static string AppHighlightBlueColor {
            get {
                return ResourceManager.GetString("AppHighlightBlueColor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to #ff0000.
        /// </summary>
        public static string AppErrorTextColor {
            get {
                return ResourceManager.GetString("AppErrorTextColor", resourceCulture);
            }
        }
    }
}
