//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace My.ClasStars.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("My.ClasStars.Resources.StringsResource", typeof(StringsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClasStars.
        /// </summary>
        public static string Classstars {
            get {
                return ResourceManager.GetString("Classstars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absent.
        /// </summary>
        public static string HP_Absent {
            get {
                return ResourceManager.GetString("HP_Absent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Engagements.
        /// </summary>
        public static string HP_AcademicEngagements {
            get {
                return ResourceManager.GetString("HP_AcademicEngagements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Negative Engagements.
        /// </summary>
        public static string HP_AcademicNegativeEngagements {
            get {
                return ResourceManager.GetString("HP_AcademicNegativeEngagements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Recorded.
        /// </summary>
        public static string HP_AttendanceRecorded {
            get {
                return ResourceManager.GetString("HP_AttendanceRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string HP_ClosePicker {
            get {
                return ResourceManager.GetString("HP_ClosePicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demographics.
        /// </summary>
        public static string HP_Demographics {
            get {
                return ResourceManager.GetString("HP_Demographics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagements Rating.
        /// </summary>
        public static string HP_EngagementsChart {
            get {
                return ResourceManager.GetString("HP_EngagementsChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellent.
        /// </summary>
        public static string HP_Excellent {
            get {
                return ResourceManager.GetString("HP_Excellent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fair.
        /// </summary>
        public static string HP_Fair {
            get {
                return ResourceManager.GetString("HP_Fair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good.
        /// </summary>
        public static string HP_Good {
            get {
                return ResourceManager.GetString("HP_Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inclusitivity Quotient.
        /// </summary>
        public static string HP_InclusitivityQuotient {
            get {
                return ResourceManager.GetString("HP_InclusitivityQuotient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string HP_Information {
            get {
                return ResourceManager.GetString("HP_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item #2.
        /// </summary>
        public static string HP_MenuItem_2 {
            get {
                return ResourceManager.GetString("HP_MenuItem#2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item #3.
        /// </summary>
        public static string HP_MenuItem_3 {
            get {
                return ResourceManager.GetString("HP_MenuItem#3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Needs Support.
        /// </summary>
        public static string HP_NeedsSupport {
            get {
                return ResourceManager.GetString("HP_NeedsSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neg.
        /// </summary>
        public static string HP_Neg {
            get {
                return ResourceManager.GetString("HP_Neg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative Engagements.
        /// </summary>
        public static string HP_NegativeEngagements {
            get {
                return ResourceManager.GetString("HP_NegativeEngagements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no data returned for the selected request..
        /// </summary>
        public static string HP_NOChartDetailsfound {
            get {
                return ResourceManager.GetString("HP_NOChartDetailsfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string HP_Overview {
            get {
                return ResourceManager.GetString("HP_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pos.
        /// </summary>
        public static string HP_Pos {
            get {
                return ResourceManager.GetString("HP_Pos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positive Engagements.
        /// </summary>
        public static string HP_PositiveEngagements {
            get {
                return ResourceManager.GetString("HP_PositiveEngagements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positivity Quotient.
        /// </summary>
        public static string HP_PositivityQuotient {
            get {
                return ResourceManager.GetString("HP_PositivityQuotient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properly Engaged.
        /// </summary>
        public static string HP_ProperlyEngaged {
            get {
                return ResourceManager.GetString("HP_ProperlyEngaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string HP_SelectDate {
            get {
                return ResourceManager.GetString("HP_SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date Range.
        /// </summary>
        public static string HP_SelectDateRange {
            get {
                return ResourceManager.GetString("HP_SelectDateRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Dates.
        /// </summary>
        public static string HP_SelectDates {
            get {
                return ResourceManager.GetString("HP_SelectDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Pictures.
        /// </summary>
        public static string HP_SelectPictures {
            get {
                return ResourceManager.GetString("HP_SelectPictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session.
        /// </summary>
        public static string HP_Session {
            get {
                return ResourceManager.GetString("HP_Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severe.
        /// </summary>
        public static string HP_Severe {
            get {
                return ResourceManager.GetString("HP_Severe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string HP_Students {
            get {
                return ResourceManager.GetString("HP_Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teachers.
        /// </summary>
        public static string HP_Teachers {
            get {
                return ResourceManager.GetString("HP_Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracking Data.
        /// </summary>
        public static string HP_TrackingData {
            get {
                return ResourceManager.GetString("HP_TrackingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string HP_Warning {
            get {
                return ResourceManager.GetString("HP_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Login.
        /// </summary>
        public static string Pleaselogin {
            get {
                return ResourceManager.GetString("Pleaselogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View our Privacy Policy.
        /// </summary>
        public static string PrivacyLink {
            get {
                return ResourceManager.GetString("PrivacyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a existing user or login a user below..
        /// </summary>
        public static string selectionmessage {
            get {
                return ResourceManager.GetString("selectionmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string StudentList_PersonID {
            get {
                return ResourceManager.GetString("StudentList_PersonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No User Found. Please Contact Admin....
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Students.
        /// </summary>
        public static string ViewStudents {
            get {
                return ResourceManager.GetString("ViewStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ClasStars.
        /// </summary>
        public static string WelcomeClasstar {
            get {
                return ResourceManager.GetString("WelcomeClasstar", resourceCulture);
            }
        }
    }
}
